### ISSUE TITLE
ntrdma-lib can't be build against rdma-core: <infiniband/driver.h> not found

### ISSUE THREAD

**Issue by glimchb** [ntrdma/ntrdma-lib#1]
git clone https://github.com/ntrdma/ntrdma-lib
...
./configure --libdir=/usr/lib64

```
checking infiniband/driver.h usability... no
checking infiniband/driver.h presence... no
checking for infiniband/driver.h... no
configure: error: <infiniband/driver.h> not found.  Is libibverbs installed?
```

**Comment by glimchb** [comment]
Duplicated with https://github.com/ntrdma/ntrdma/issues/17

**Comment by glimchb** [comment]
@allenbh 

The rdma-core package replaces various (lib)ibverbs and (lib)rdmacm packages.
Part of the change, <infiniband/driver.h> is no longer shipped even in devel packages.

So what should be the future of https://github.com/ntrdma/ntrdma-lib ?
Should it be merged to https://github.com/linux-rdma/rdma-core ?

What do you think should happen here?

Thanks,

**Comment by allenbh** [comment]
Yes, it should be made to build with rdma-core, and updated for changes in the current driver interface.

**Comment by glimchb** [comment]
Thanks. Few more questions:

1. Should ntrdma-lib still remain as a separate git project or PR to push it to rdma-core project?
2. Should same branches here as in rdma-core (stable-v15, stable-v16, stable-v17, stable-v18, stable-v19, stable-v20, stable-v21,...) be created in ntrdma-lib in order to support different stable branches of rdma-core or just master is enough?

**Comment by allenbh** [comment]
In my opinion, if libntrdma was replaced by a generic user space library that uses system calls for all verbs, that would be better, and possibly also useful for other drivers. That is all libntrdma does, except that it recognises devices named ntrdma.

**Comment by glimchb** [comment]
Sounds interesting... Will think about that...
